language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '10'
  - '12'
script:
  - yarn test
  - yarn run build
  - commitlint-travis
after_success:
  - yarn global add travis-deploy-once@4
  - travis-deploy-once "yarn run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
